version: '3.8'

services:
  db:
    container_name: erderpladsihavnen_db
    build:
      context: .
      dockerfile: Dockerfile.db 
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - erderpladsihavnen_db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - backend_network
    # env_file:
      # - /etc/unisoft/config/.env

  backend:
    container_name: erderpladsihavnen_backend
    build:
      context: .
      dockerfile: Dockerfile.backend
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    ports:
      - "3003:3003"
    depends_on:
      - db
    networks:
      - backend_network
    # env_file:
      # - /etc/unisoft/config/.env
    volumes:
      - /etc/ssl/pladsihavnen:/usr/src/app/ssl
      - .env:/usr/src/app/.env
      - ./backend/.ssl:/usr/src/app/.ssl

volumes:
  erderpladsihavnen_db:

networks:
  backend_network:
