version: '3.8'

services:
  db:
    container_name: erderpladsihavnen_db
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - erderpladsihavnen_db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - backend_network

  backend:
    container_name: erderpladsihavnen_backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - backend_network

volumes:
  erderpladsihavnen_db:

networks:
  backend_network:
